In [14]:
import numpy as np

#fungsi aktivasi yang akan dipanggil
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# mendefinisikan class neural network
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # menginisialisasi  bobot dari input ke hidden
        self.weights_input_hidden = np.array([[0.5, 0.2, -0.3, 0.3, 0.1], [0.7, -0.4, 0.6, 0.8, 0.1]])

        # menginisialisasi  bobot dari hidden ke output
        self.weights_hidden_output = np.array([[0.1, -0.2], [0.4, 0.3], [0.5, 0.7], [0.5, -0.7], [0.3, 0.6]])

        # menginisialisasi bias
        self.bias_hidden = np.array([0.7, 0.7, 0.7, 0.7, 0.7])  # Bias untuk hiden
        self.bias_output = np.array([0.9, 0.9])       # Bias untuk output

    def forward(self, inputs):
        # Forward propagation
        self.hidden_input = np.dot(inputs, self.weights_input_hidden) + self.bias_hidden
        self.hidden_output = sigmoid(self.hidden_input)
        self.output_input = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output
        self.predicted_output = sigmoid(self.output_input)
        return self.predicted_output

    def backward(self, inputs, target, learning_rate):
        # Backpropagation
        error = target - self.predicted_output
        delta_output = error * sigmoid_derivative(self.predicted_output)

        error_hidden = delta_output.dot(self.weights_hidden_output.T)
        delta_hidden = error_hidden * sigmoid_derivative(self.hidden_output)

        # Update weights
        self.weights_hidden_output += np.outer(self.hidden_output, delta_output) * learning_rate
        self.weights_input_hidden += np.outer(inputs, delta_hidden) * learning_rate

    def train(self, training_data, targets, epochs, learning_rate):
        for epoch in range(epochs):
            total_error = 0  # Initialize total error for the epoch
            for i in range(len(training_data)):
                inputs = training_data[i]
                target = targets[i]
                self.forward(inputs)
                self.backward(inputs, target, learning_rate)
                total_error += np.mean(np.square(target - self.predicted_output))  # Squared Error


            # Print error setiap 100 iterasi aja
            if epoch % 5 == 0:
                print(f"\nBobot dari input ke hidden:\n{nn.weights_input_hidden}")
                print(f"Epoch {epoch}, Average Error: {total_error / len(training_data)}")
                print(f"\nBobot dari input ke hidden:\n{nn.weights_input_hidden}")


    def predict(self, inputs):
        return self.forward(inputs)

# Input atau nilai x nya.
training_data = np.array([[0, 5]])
targets = np.array([2])

input_size = 2
hidden_size = 5
output_size = 1
learning_rate = 0.99
epochs = 100

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(training_data, targets, epochs, learning_rate)

# Test network
for inputs in training_data:
    prediction = nn.predict(inputs)
    print(f"Input: {inputs}, Predicted Output: {prediction}")



Bobot dari input ke hidden:
[[ 0.5         0.2        -0.3         0.3         0.1       ]
 [ 0.69753336 -0.31574721  0.62293159  0.79530256  0.23826128]]
Epoch 0, Average Error: 1.3498424386802785

Bobot dari input ke hidden:
[[ 0.5         0.2        -0.3         0.3         0.1       ]
 [ 0.69753336 -0.31574721  0.62293159  0.79530256  0.23826128]]

Bobot dari input ke hidden:
[[ 0.5         0.2        -0.3         0.3         0.1       ]
 [ 0.70453876 -0.06750459  0.6673989   0.79650214  0.3977657 ]]
Epoch 5, Average Error: 1.0644452299275455

Bobot dari input ke hidden:
[[ 0.5         0.2        -0.3         0.3         0.1       ]
 [ 0.70453876 -0.06750459  0.6673989   0.79650214  0.3977657 ]]

Bobot dari input ke hidden:
[[ 0.5         0.2        -0.3         0.3         0.1       ]
 [ 0.71054507  0.05693929  0.6862468   0.7995359   0.44835189]]
Epoch 10, Average Error: 1.0351707547673947

Bobot dari input ke hidden:
[[ 0.5         0.2        -0.3         0.3         0.1       

In [13]:
import numpy as np

#fungsi aktivasi yang akan dipanggil
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# mendefinisikan class neural network
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # menginisialisasi  bobot dari input ke hidden
        self.weights_input_hidden = np.array([[0.5, 0.2, -0.3, 0.3], [0.7, -0.4, 0.6, 0.8]])

        # menginisialisasi  bobot dari hidden ke output
        self.weights_hidden_output = np.array([[0.1, -0.2], [0.4, 0.3], [0.5, 0.7], [0.5, -0.7], [0.3, 0.6]])

        # menginisialisasi bias
        self.bias_hidden = np.array([0.7, 0.7, 0.7, 0.7])  # Bias untuk hiden, adjusted to match the number of hidden nodes
        self.bias_output = np.array([0.9, 0.9])       # Bias untuk output

    def forward(self, inputs):
        # Forward propagation
        self.hidden_input = np.dot(inputs, self.weights_input_hidden) + self.bias_hidden
        self.hidden_output = sigmoid(self.hidden_input)
        self.output_input = np.dot(self.hidden_output, self.weights_hidden_output) + self.bias_output
        self.predicted_output = sigmoid(self.output_input)
        return self.predicted_output

    def backward(self, inputs, target, learning_rate):
        # Backpropagation
        error = target - self.predicted_output
        delta_output = error * sigmoid_derivative(self.predicted_output)

        error_hidden = delta_output.dot(self.weights_hidden_output.T)
        delta_hidden = error_hidden * sigmoid_derivative(self.hidden_output)

        # Update weights
        self.weights_hidden_output += np.outer(self.hidden_output, delta_output) * learning_rate
        self.weights_input_hidden += np.outer(inputs, delta_hidden) * learning_rate

    def train(self, training_data, targets, epochs, learning_rate):
        for epoch in range(epochs):
            total_error = 0  # Initialize total error for the epoch
            for i in range(len(training_data)):
                inputs = training_data[i]
                target = targets[i]
                self.forward(inputs)
                self.backward(inputs, target, learning_rate)
                total_error += np.mean(np.square(target - self.predicted_output))  # Squared Error


            # Print error setiap 100 iterasi aja
            if epoch % 5 == 0:
                print(f"\nBobot dari input ke hidden:\n{nn.weights_input_hidden}")
                print(f"Epoch {epoch}, Average Error: {total_error / len(training_data)}")
                print(f"\nBobot dari input ke hidden:\n{nn.weights_input_hidden}")


    def predict(self, inputs):
        return self.forward(inputs)

# Input atau nilai x nya.
training_data = np.array([[0, 5]])
targets = np.array([2])

input_size = 2
hidden_size = 5 # Adjusted hidden size to match the weights
output_size = 1
learning_rate = 0.99
epochs = 100

nn = NeuralNetwork(input_size, hidden_size, output_size)
nn.train(training_data, targets, epochs, learning_rate)

# Test network
for inputs in training_data:
    prediction = nn.predict(inputs)
    print(f"Input: {inputs}, Predicted Output: {prediction}")

ValueError: shapes (4,) and (5,2) not aligned: 4 (dim 0) != 5 (dim 0)